### ISSUE TITLE
download script puts metadata in wrong schema directory

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metadig#27]
The script for randomly pulling metadata from DataONE (described in issue #2 ) seems to be having trouble mixing up several dialects into the same directory, namely FGDC CSDGM, BDP, and the Mercury extensions to CSDGM.  Clarify when and how this happens, and fix it so that each of these document types has its own directory.

**Comment by amoeba** [comment]
This issue is caused by the way the format subfolder name is determined. The script assumes that the document at a particular PID is of the format the Solr index says it is. It does not inspect the contents of the document to determine its format. In the case of the above format types, the script was doing what it was designed to do, namely putting the documents in a folder based upon their format in the Solr index.

It turned out that some of these documents are of different formats than what's on the Solr index. Or, more accurately, the format of these files on the Solr index was just not the most appropriate format for them and this caused confusion for users of the script.

The solution for now is to (1) know this happens and (2) move sampled files into the correct subfolder manually after sampling has taken place. The script can be modified to determine formats in a more advanced way but that was not deemed necessary right now.
